<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60142" started-at="2019-05-20T06:39:58Z" finished-at="2019-05-20T06:40:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60142" started-at="2019-05-20T06:39:58Z" finished-at="2019-05-20T06:40:59Z">
      <class name="userTest.VerifyLogin">
        <test-method status="PASS" signature="reportSetUp()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="reportSetUp" is-config="true" duration-ms="379" started-at="2019-05-20T06:39:58Z" finished-at="2019-05-20T06:39:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSetUp -->
        <test-method status="PASS" signature="initialization()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="initialization" is-config="true" duration-ms="51540" started-at="2019-05-20T06:39:58Z" finished-at="2019-05-20T06:40:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="beforePrint()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="beforePrint" is-config="true" duration-ms="1" started-at="2019-05-20T06:40:50Z" finished-at="2019-05-20T06:40:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforePrint -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="verifyLogin" duration-ms="7680" started-at="2019-05-20T06:40:50Z" finished-at="2019-05-20T06:40:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text not matched - Test failed expected [Quick Link] but found [Quick Links]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text not matched - Test failed expected [Quick Link] but found [Quick Links]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at utility.CommonMethods.getText(CommonMethods.java:27)
at userTest.VerifyLogin.verifyLogin(VerifyLogin.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="afterMethod" is-config="true" duration-ms="630" started-at="2019-05-20T06:40:58Z" finished-at="2019-05-20T06:40:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=FAILURE method=VerifyLogin.verifyLogin()[pri:0, instance:userTest.VerifyLogin@5c3bd550] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="tearDown" is-config="true" duration-ms="223" started-at="2019-05-20T06:40:58Z" finished-at="2019-05-20T06:40:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="extentClose()[pri:0, instance:userTest.VerifyLogin@5c3bd550]" name="extentClose" is-config="true" duration-ms="1027" started-at="2019-05-20T06:40:59Z" finished-at="2019-05-20T06:41:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentClose -->
      </class> <!-- userTest.VerifyLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
